# Makefile for macOS

BINS := coreaudio-dev-list coreaudio-record coreaudio-play

all: $(BINS)

clean:
	rm $(BINS)

coreaudio-%: coreaudio-%.c
	clang -g $< -o $@ -framework CoreFoundation -framework CoreAudio
